spring:
  application:
    name: internet-banking-backend
  datasource:
    url: jdbc:mysql://localhost:3306/novabank?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 181070
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        globally_quoted_identifiers: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: adminnovabank@gmail.com      # Replace with your Gmail address
    password: zjyakxbwfufjaslg             # Replace with Gmail App Password (not login password)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 9098
security:
  jwt:
    secret: RnVsbFN0YWNrLUludGVybmV0LUJhbmtpbmctSldULVNlY3JldC1Gb3ItTm92YUJhbmstMjAyNg==
    expiration-ms: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
